In [29]:
from sklearn import datasets
import numpy as np
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [20]:
dataset = datasets.load_iris()
x,y=dataset.data,dataset.target

In [21]:
model = GaussianNB()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
y_predict=model.predict(x_test)

In [30]:
print('Mean absolute error:',metrics.mean_absolute_error(y_test,y_predict))
print('Mean squared error:',metrics.mean_squared_error(y_test,y_predict))
print('Root Mean squared error:',np.sqrt(metrics.mean_squared_error(y_test,y_predict)))

Mean absolute error: 0.03333333333333333
Mean squared error: 0.03333333333333333
Root Mean squared error: 0.18257418583505536


In [26]:
print(metrics.classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



In [27]:
print(metrics.confusion_matrix(y_test, y_predict))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
